/**
 * 部署：把 active 规则同步为系统 crontab 条目 + wrapper 脚本。
 * wrapper 由 cron 在进程外调用，负责 headless 运行与运行记录 manifest。
 */

import { spawn } from 'node:child_process'
import { chmod, mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { resolveDshCommand, type DshResolution } from './dsh-resolve.ts'
import type { CronDefinition } from './types.ts'
import { normalizeCron } from './cron.ts'
import type { PluginPaths } from './home.ts'

export const CRONTAB_MARKER_START = '# >>> dsh-cron-scheduler managed block >>>'
export const CRONTAB_MARKER_END = '# <<< dsh-cron-scheduler managed block <<<'

export interface DeployOptions {
  readonly paths: PluginPaths
  readonly dshHome: string
  /** 显式 dsh 命令；缺省时自动探测。 */
  readonly dshCommand: string | undefined
  readonly profile: string
}

export interface DeployResult {
  readonly deployedAt: string | null
  readonly error: string | null
}

/** 单引号包裹任意内容（bash 安全）。 */
function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/** 解析 wrapper 将使用的 dsh 命令（含自动生成 shim）。 */
export function resolveDshForDeploy(opts: DeployOptions): DshResolution {
  return resolveDshCommand(opts.dshCommand, opts.paths)
}

/**
 * 生成 wrapper 脚本文本（bash 3.2 兼容，macOS /bin/bash 可跑）。
 * 引号策略：静态路径用单引号（shQuote）；含 shell 展开的用双引号。
 * @internal 导出仅用于测试。
 */
export function wrapperScript(
  definition: CronDefinition,
  opts: DeployOptions,
  dsh: { readonly command: string },
): string {
  const { paths } = opts
  return [
    '#!/bin/bash',
    '# generated by dsh-cron-scheduler — do not edit',
    'set -u',
    `export HOME=${shQuote(process.env.HOME ?? '')}`,
    `export PATH=${shQuote(process.env.PATH ?? '')}`,
    `export DSH_HOME=${shQuote(opts.dshHome)}`,
    `export DSH_PERMISSION_MODE=${shQuote(definition.permission)}`,
    '',
    `AUTOMATION_ID=${shQuote(definition.id)}`,
    'TRIGGER=${1:-schedule}',
    'RUN_ID="${AUTOMATION_ID}-$(date +%Y%m%d-%H%M%S)-$$"',
    'SCHEDULED_FOR=$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    `MANIFEST="${paths.runs}/${'$'}{RUN_ID}.json"`,
    `TASK_FILE=${shQuote(join(paths.tasks, `${definition.id}.txt`))}`,
    `LOG_FILE=${shQuote(join(paths.logs, `${definition.id}.log`))}`,
    `LOCK_DIR=${shQuote(join(paths.locks, `${definition.id}.lock`))}`,
    `WORKDIR=${shQuote(definition.cwd)}`,
    `DSH=${shQuote(dsh.command)}`,
    `PROFILE=${shQuote(opts.profile)}`,
    '',
    'write_manifest() {',
    '  local status="$1" started="$2" finished="$3" error="$4"',
    '  local started_json finished_json error_json',
    '  if [ -z "$started" ]; then started_json="null"; else started_json="\\"$started\\""; fi',
    '  if [ -z "$finished" ]; then finished_json="null"; else finished_json="\\"$finished\\""; fi',
    '  if [ -z "$error" ]; then error_json="null"; else error_json="\\"$error\\""; fi',
    '  printf \'{"id":"%s","automationId":"%s","trigger":"%s","scheduledFor":"%s","status":"%s","sessionId":null,"startedAt":%s,"finishedAt":%s,"summary":null,"error":%s,"unread":true}\\n\' \\',
    '    "$RUN_ID" "$AUTOMATION_ID" "$TRIGGER" "$SCHEDULED_FOR" "$status" "$started_json" "$finished_json" "$error_json" > "$MANIFEST"',
    '}',
    '',
    `mkdir -p ${shQuote(paths.runs)} ${shQuote(paths.logs)} ${shQuote(paths.locks)} 2>/dev/null`,
    'write_manifest "queued" "" "" ""',
    'echo "$RUN_ID"',
    'if ! mkdir "$LOCK_DIR" 2>/dev/null; then',
    '  write_manifest "skipped" "" "" "overlap"',
    '  exit 0',
    'fi',
    'trap \'rmdir "$LOCK_DIR" 2>/dev/null\' EXIT',
    'STARTED=$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    'write_manifest "running" "$STARTED" "" ""',
    `cd "$WORKDIR" || { write_manifest "failed" "$STARTED" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "cannot cd to workspace"; exit 1; }`,
    '"$DSH" --profile "$PROFILE" "$(cat "$TASK_FILE")" >> "$LOG_FILE" 2>&1',
    'CODE=$?',
    'FINISHED=$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    'if [ "$CODE" -eq 0 ]; then',
    '  write_manifest "succeeded" "$STARTED" "$FINISHED" ""',
    'else',
    '  write_manifest "failed" "$STARTED" "$FINISHED" "exit ${CODE}"',
    'fi',
    'exit "$CODE"',
    '',
  ].join('\n')
}

interface CronResult {
  readonly stdout: string
  readonly stderr: string
  readonly code: number
}

/** 运行 crontab 命令；写模式必须显式 end stdin（否则 crontab 会阻塞等 EOF）。 */
function runCrontab(args: readonly string[], input?: string): Promise<CronResult> {
  return new Promise((resolve, reject) => {
    const child = spawn('crontab', args, { stdio: ['pipe', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk: Buffer) => { stdout += chunk.toString() })
    child.stderr.on('data', (chunk: Buffer) => { stderr += chunk.toString() })
    child.on('error', reject)
    child.on('close', (code) => resolve({ stdout, stderr, code: code ?? -1 }))
    child.stdin.end(input ?? '')
  })
}

async function readCrontab(): Promise<string[]> {
  try {
    const result = await runCrontab(['-l'])
    if (result.code === 0) return result.stdout.split('\n')
    return []
  } catch {
    // 无 crontab 或读取失败：按空处理
    return []
  }
}

async function writeCrontab(lines: readonly string[]): Promise<void> {
  const result = await runCrontab(['-'], `${lines.join('\n')}\n`)
  if (result.code !== 0) {
    throw new Error(`crontab 写入失败: ${result.stderr.trim() || `exit ${result.code}`}`)
  }
}

function stripManagedBlock(lines: readonly string[]): string[] {
  const kept: string[] = []
  let inside = false
  for (const line of lines) {
    if (line.trim() === CRONTAB_MARKER_START) { inside = true; continue }
    if (line.trim() === CRONTAB_MARKER_END) { inside = false; continue }
    if (!inside) kept.push(line)
  }
  return kept.filter((line, index, all) => !(line.trim() === '' && (index === 0 || all[index - 1]?.trim() === '')))
}

/**
 * 仅生成 wrapper 与 task 文件（不动 crontab）。@internal 导出用于测试与分步部署。
 */
export async function generateWrapperFiles(
  definitions: readonly CronDefinition[],
  opts: DeployOptions,
): Promise<Map<string, DeployResult>> {
  const { paths } = opts
  const results = new Map<string, DeployResult>()
  const dsh = resolveDshCommand(opts.dshCommand, paths)
  const active = definitions.filter(definition => definition.status === 'active')
  const inactive = definitions.filter(definition => definition.status !== 'active')

  try {
    await mkdir(paths.wrappers, { recursive: true })
    await mkdir(paths.tasks, { recursive: true })
    await mkdir(paths.logs, { recursive: true })
    await mkdir(paths.runs, { recursive: true })
    await mkdir(paths.locks, { recursive: true })
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    for (const definition of definitions) {
      results.set(definition.id, { deployedAt: null, error: `无法创建目录: ${message}` })
    }
    return results
  }

  for (const definition of active) {
    try {
      const wrapperPath = join(paths.wrappers, `${definition.id}.sh`)
      await writeFile(wrapperPath, wrapperScript(definition, opts, dsh), { encoding: 'utf8', mode: 0o755 })
      await chmod(wrapperPath, 0o755)
      const taskText = `[dsh-cron:task=${definition.id}] ${definition.name}\n\n${definition.prompt}`
      await writeFile(join(paths.tasks, `${definition.id}.txt`), taskText, 'utf8')
      results.set(definition.id, { deployedAt: null, error: null })
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      results.set(definition.id, { deployedAt: null, error: `wrapper 生成失败: ${message}` })
    }
  }
  for (const definition of inactive) {
    await rm(join(paths.wrappers, `${definition.id}.sh`), { force: true }).catch(() => undefined)
    await rm(join(paths.tasks, `${definition.id}.txt`), { force: true }).catch(() => undefined)
    results.set(definition.id, { deployedAt: null, error: null })
  }
  // 清理孤儿文件：wrapper/task 目录里不属于任何现有定义的文件（删除规则后残留）。
  await pruneOrphans(paths, new Set(definitions.map(definition => definition.id)))
  return results
}

async function pruneOrphans(paths: PluginPaths, known: ReadonlySet<string>): Promise<void> {
  for (const dir of [paths.wrappers, paths.tasks]) {
    let entries: string[]
    try {
      entries = await readdir(dir)
    } catch {
      continue
    }
    for (const entry of entries) {
      const id = entry.endsWith('.sh')
        ? entry.slice(0, -3)
        : entry.endsWith('.txt')
          ? entry.slice(0, -4)
          : undefined
      if (id === undefined || known.has(id)) continue
      await rm(join(dir, entry), { force: true }).catch(() => undefined)
    }
  }
}

/**
 * 同步全部部署：active → wrapper+task 文件 + crontab 条目；paused/删除 → 移除文件与条目。
 * @returns 每个规则 id 的部署结果。
 */
export async function syncDeployments(
  definitions: readonly CronDefinition[],
  opts: DeployOptions,
): Promise<Map<string, DeployResult>> {
  const { paths } = opts
  const results = await generateWrapperFiles(definitions, opts)
  const active = definitions.filter(definition => definition.status === 'active')
  const now = new Date().toISOString()

  // crontab 同步
  let crontabError: string | null = null
  try {
    const existing = await readCrontab()
    const entries = active
      .sort((a, b) => a.id.localeCompare(b.id))
      .map(definition => {
        const cron = normalizeCron(definition.cron)
        const wrapper = join(paths.wrappers, `${definition.id}.sh`)
        const log = join(paths.logs, `${definition.id}.log`)
        const cronPart = cron === '@reboot' ? '@reboot' : cron
        return `${cronPart} /bin/bash ${wrapper} >> ${log} 2>&1`
      })
    const block = entries.length === 0
      ? []
      : [CRONTAB_MARKER_START, ...entries, CRONTAB_MARKER_END]
    const next = stripManagedBlock(existing).concat(block)
    // 仅当"原内容或目标内容有实质行"时才写入：避免空 crontab 上无意义地建文件，
    // 同时保证删除最后一条规则时能真正清掉遗留块。
    const originalHasContent = existing.some(line => line.trim() !== '')
    const nextHasContent = next.some(line => line.trim() !== '')
    if (originalHasContent || nextHasContent) {
      await writeCrontab(next)
    }
  } catch (error) {
    crontabError = error instanceof Error ? error.message : String(error)
  }

  const deployedAt = crontabError === null ? now : null
  for (const definition of active) {
    const prior = results.get(definition.id)
    results.set(definition.id, {
      deployedAt,
      error: crontabError ?? prior?.error ?? null,
    })
  }
  return results
}

/**
 * 手动触发一条规则：以指定 trigger 启动其 wrapper。
 * 只等待 wrapper 吐出的第一行 runId 即返回，**不等待进程结束、不设超时**
 * （wrapper 内部执行 headless 长任务，可能运行数分钟；终止它会把运行打断）。
 */
export function spawnWrapper(
  paths: PluginPaths,
  definitionId: string,
  trigger: 'schedule' | 'manual',
): Promise<{ readonly runId: string | null; readonly error: string | null }> {
  const wrapper = join(paths.wrappers, `${definitionId}.sh`)
  return new Promise((resolve) => {
    let settled = false
    const finish = (value: { readonly runId: string | null; readonly error: string | null }): void => {
      if (!settled) {
        settled = true
        resolve(value)
      }
    }
    let child
    try {
      child = spawn('/bin/bash', [wrapper, trigger], { stdio: ['ignore', 'pipe', 'inherit'] })
    } catch (error) {
      finish({ runId: null, error: error instanceof Error ? error.message : String(error) })
      return
    }
    let stdout = ''
    child.stdout.on('data', (chunk: Buffer) => {
      stdout += chunk.toString()
      const line = stdout.split('\n').find(value => value.trim() !== '')
      if (line !== undefined) finish({ runId: line.trim(), error: null })
    })
    child.on('error', (error) => finish({ runId: null, error: error.message }))
    child.on('exit', (code) => {
      // 未在 stdout 收到 runId 就退出（wrapper 启动即失败）时才报错。
      if (!settled) {
        finish({ runId: null, error: code === null ? 'wrapper 启动失败' : `wrapper 退出码 ${String(code)}` })
      }
    })
  })
}
